/** @module @brass/window/types
 *
 * Core type definitions for window applications.
 *
 * Includes application initialization options, window initialization options, window state, and window event map.
 *
 * @see https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-createwindowexw
 */

/** Application initialization options */
export interface AppOptions {
    /** Taskbar icon path */
    iconPath?: string;
    /** Window title bar icon path */
    iconSmPath?: string;
}

/** Window initialization options */
export interface WindowOptions {
    /** Window title */
    title: string;
    /** Window unique identifier */
    id: string;
    /** Window width (pixels, default 800) */
    width?: number;
    /** Window height (pixels, default 600) */
    height?: number;
    /** Window X coordinate (default 0) */
    x?: number;
    /** Window Y coordinate (default 0) */
    y?: number;
}

/** Window state */
export interface WindowState {
    /** Whether the window is maximized */
    isMaximized: boolean;
    /** Whether the window is minimized */
    isMinimized: boolean;
    /** Whether the window is fullscreen */
    isFullscreen: boolean;
    /** Whether the window is always on top */
    isAlwaysOnTop: boolean;
    /** Whether the window is resizable */
    isResizeable: boolean;
    /** Whether the window is borderless */
    isBorderless: boolean;
    /** Whether the window is locked (mouse locked, for games) */
    isLocked: boolean;
    /** Whether the window is visible */
    isVisible: boolean;

    /** Whether the window IME (Input Method Editor) is enabled */
    isImeEnabled: boolean;

    /** Whether the mouse cursor is visible */
    isCursorVisible: boolean;

    /** Whether the window is centered */
    isCentered: boolean;
}

/**
 * Window event map.
 *
 * Defines all supported event names and their corresponding callback data types.
 * Keys are event names, values are the data passed to callbacks when the event fires.
 *
 * @see WindowEvents Used as a TypedEmitter generic parameter
 * @example
 * ```ts
 * // 监听 resize 事件
 * window.addEventListener("resize", ({ width, height }) => {
 *   console.log(`窗口调整为 ${width}x${height}`);
 * });
 * ```
 */
export interface WindowEvents {
    resize: { width: number; height: number };
    minimize: void;
    maximize: void;
    move: { x: number; y: number };

    close: void;
    focus: void;
    blur: void;
    restore: void;
    destroy: void;

    mouselock: { deltaX: number; deltaY: number; };
    mousemove: { x: number; y: number; };
    mousewheel: { delta: number; };

    click: { x: number; y: number; button: number; };
    dblclick: { x: number; y: number; button: number; };

    keydown: {
        /** Virtual-Key Code, see {@link VirtualKeys} */
        code: number;
        /** Translated character based on the current keyboard layout (empty string for non-printable keys) */
        char: string;
        /** Repeat count (generated by key message time intervals) */
        repeat: number;
        /** OEM scan code (keyboard hardware scan code) */
        scanCode: number;
        /** Whether it is an extended key (e.g., right Alt/Ctrl) */
        extended: boolean;
        /** Whether the Alt key is pressed */
        altKey: boolean;
        /** Whether the Ctrl key is pressed */
        ctrlKey: boolean;
        /** Whether the Shift key is pressed */
        shiftKey: boolean;
    };

    keyup: {
        /** Virtual-Key Code, see {@link VirtualKeys} */
        code: number;
        /** Translated character based on the current keyboard layout (empty string for non-printable keys) */
        char: string;
        /** Repeat count (typically 1) */
        repeat: number;
        /** OEM scan code */
        scanCode: number;
        /** Whether it is an extended key */
        extended: boolean;
        /** Whether the Alt key is pressed */
        altKey: boolean;
        /** Whether the Ctrl key is pressed */
        ctrlKey: boolean;
        /** Whether the Shift key is pressed */
        shiftKey: boolean;
    };

    keypress: {
        /** Actual input character (converted from key message by `TranslateMessage`, supports IME input) */
        char: string;
        /** Repeat count */
        repeat: number;
        /** OEM scan code */
        scanCode: number;
        /** Whether it is an extended key */
        extended: boolean;
        /** Whether the Alt key is pressed */
        altKey: boolean;
        /** Whether the Ctrl key is pressed */
        ctrlKey: boolean;
        /** Whether the Shift key is pressed */
        shiftKey: boolean;
    };

    /** IME composition starts (e.g., opening the Pinyin input method candidate window) */
    compositionstart: void;
    /** IME composition update (triggered when candidate content changes) */
    compositionupdate: { data: string };
    /** IME composition ends (`data` is the final committed string) */
    compositionend: { data: string };
}